### ISSUE TITLE
go to OuiShareFest?

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#114]
http://2015.ouisharefest.com/

> In its 3rd year, the event will gather 1000 people to explore the future of movements such as collaborative consumption, open source, makers and fablabs, coworking, crowdfunding, alternative currencies and horizontal governance - movements that are transforming cities, organizations and civic action worldwide.

Speakers get free admission (€150), but still have to pay for travel and accommodations.

**Comment by whit537** [comment]
> The OuiShare Awards aim to put exceptional collaborative economy initiatives from across the globe in the spotlight and provide them with support to develop further. The award ceremony will take place during OuiShare Fest in Paris, May 20-22 at the Cabaret Sauvage. **All nominees will be invited to the festival to present their projects.**

http://magazine.ouishare.net/2015/02/ready-for-the-ouishare-awards-2015-applications-start-now/

**Comment by whit537** [comment]
Here's the application:

http://awards.ouishare.net/2015/applications/

**Comment by whit537** [comment]
Current application status:

![screen shot 2015-02-26 at 4 53 20 pm](https://cloud.githubusercontent.com/assets/134455/6402757/1ba6c344-bdd8-11e4-94b4-be4617aa511a.png)
![screen shot 2015-02-26 at 4 54 57 pm](https://cloud.githubusercontent.com/assets/134455/6402774/40feebb2-bdd8-11e4-9b6b-2506fcda2d0a.png)

**Comment by whit537** [comment]
I'm working on: "Brief summary of your initiative[;] Please give a short overview of your activity, explain the problem identified and your solution."

Here's what I have so far:

>Gratipay is a crowdfunding platform for the common good. Our mission is to enable an economy of gratitude, generosity, and love.
>
PROBLEM: Individuals in our economy are not free enough.
>
As an individual consumer, I can passively accept or reject a price offered, and in limited cases I can competitively negotiate a price, but I am not fully free to actively, collaboratively name my own price.
>
Similarly, as an individual worker, I can passively accept or reject and in some cases negotiate a wage, but I am not fully free to actively, collaboratively set my own wages.
>
SOLUTION: Give individuals freedom to actively determine their own prices and wages.
>
What makes Gratipay unique?
>
First, we don't skim off the top! Instead, we depend on voluntary payments just like any other organization on our platform. Gratipay is funded on Gratipay.
>
Second, our business processes and our source code are as open and transparent as possible.
>
Third, we've developed an innovative revenue distribution model best described as "take-what-you-need." Under this model, jobs are as abundant as work.

**Comment by techtonik** [comment]
The travel cost for me to get there is about $120, so it might be real to meet if I find a place to stay by this day. Very cool event, I wish I could afford to get there.

I have a different view on the PROBLEM that Gratipay solves. It is that current economy will not be able to sustain the living and prevent conflicts on the planet as more and more stuff is automated. There is no mechanism to support people you're excited about if you're not a rich, and if you're rich, the chances are that your only interest is getting more money, and you don't have time to support anyone. http://www.oxfam.org/sites/www.oxfam.org/files/file_attachments/ib-wealth-having-all-wanting-more-190115-en.pdf

SOLUTION. Gratipay could solve the problem of transparency. We can help people to find themselves what they want to support, what they find useful. It may be a first building block to see how economy works in open, how its global nature hurts distribution. Gratipay can open a world of transactions, so that we can self-adjust our flows and economy to support things that economy was not designed to support. Especially economy that feel lack of resources and is susceptible to "great depression". Gratipay distribution could be a first step to build something that is resilient after money lose their value, because it has unique property of setting a personal value for things around you and letting other see it and adjust. It is not a plan or project - it is a living system that already operates openly and transparently, and provides information and open data that can be trusted.

This is my vision. Of course, there is still a long way to go for Gratipay, but we are much more further in this direction than any speakers and visionaries, because our platform is live.

**Comment by whit537** [comment]
Looks like we're not going to be able to pull off non-U.S. payouts before OuiShare (https://github.com/gratipay/gratipay.com/issues/417#issuecomment-78266767). Does that make it not worth going to? I still kind of want to go, tbh. :-(

**Comment by whit537** [comment]
Deadline for OuiShare awards applications is tomorrow.

I'm leaning against going, due to cost and we won't have the product far enough along to make it worth it. I'll be too embarrassed to show it to anyone. :-(

We also have the Balanced shutdown to contend with, and traveling would distract from that.

**Comment by whit537** [comment]
Making the call on this one. Awards application deadline is past, and we didn't submit. Let's think about this again next year when our product is further along.
