### ISSUE TITLE
budget for retreat

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#124]
I propose that this year we pay for food, etc. for the retreat out of Gratipay's operating account. Any objections? Do we want to set a budget?

**Comment by techtonik** [comment]
Take whatever it takes to get into the condition to make the Gratipay
service even more useful for everyone and not bankrupt it. =)

Paying for food and lodging is more than reasonable, because not everybody
may have sufficient income for booking a hotel and going on for expensive
foods that people may used to get on holidays. I'd even include travel
expenses, but it is unlikely to happen without depleting our safety budget.
Fixed $300 is maybe not the best option - flexibility never hurts, because
somebody needs more and somebody may need less. In any case having to
bother around money is a bad experience during hackatons, so don't
sacrifice good atmosphere for the sake of some savings. People are more
important than money.

**Comment by whit537** [comment]
Thanks for the lee-way, @techtonik. Here's what I've spent so far:

 - $15 coffee (I'm about to go pick up two dispensers from Blue Canary)
 - $230 groceries
 - $62 foam boards, tape, and power strips
 - $41 drinks at the bar last night
 - $19.99 gasoline

**Comment by whit537** [comment]
Final tally per [finances](http://inside.gratipay.com/appendices/finances): $521.45.

**Comment by clone1018** [comment]
@whit537 How did this work last year, can we proceed under the same this year or do we need to dip into personal funding?

**Comment by whit537** [comment]
Iirc we paid for a bunch of groceries (drinks? eating out?) out of Gratipay operations, and I think we can/should do the same again. Jess and I appreciated yinz's gift to us for hosting :bow:, though since you are paying to travel in the first place I don't consider it necessary.

**Comment by whit537** [comment]
Oops! Should this be on a new ticket for 2016?

**Comment by clone1018** [comment]
Yeah I was going to learn from this issue to create the new issue :p
