### ISSUE TITLE
let's talk about our takes

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#136]
It feels to me like we're due for a conversation about our team takes:

https://gratipay.com/Gratipay/members/

Now is the chance to air any resentments you may have about our current team take situation. Let's find out what each other are thinking in setting our takes where we have.

**Comment by whit537** [comment]
Let's start by getting some data on the table:

```
=> select member, ctime::date, (current_date - ctime::date) / 7 as nweeks, amount from 
current_takes where team='Gratipay' and amount > 20 order by amount desc;
┌────────────┬────────────┬────────┬────────┐
│   member   │   ctime    │ nweeks │ amount │
├────────────┼────────────┼────────┼────────┤
│ Changaco   │ 2013-12-06 │     59 │ 110.00 │
│ whit537    │ 2013-07-02 │     82 │ 110.00 │
│ rummik     │ 2013-07-02 │     82 │  32.00 │
│ rohitpaulk │ 2014-08-29 │     21 │  25.00 │
│ benhc123   │ 2014-11-10 │     11 │  24.35 │
│ techtonik  │ 2014-10-28 │     13 │  23.45 │
└────────────┴────────────┴────────┴────────┘
(6 rows)
```

**Comment by whit537** [comment]
@rummik had another job for a while and then came back, so I'm going to use `2014-12-01` and `nweeks=8` for her, because Dec 1 is when she started upping her take again.

**Comment by Changaco** [comment]
The takes of @benhc123 and @techtonik might be a little high compared to their actual contributions, but of course that's not the only metric to consider.

**Comment by whit537** [comment]
> compared to their actual contributions

To get a sense of "actual contributions," I've looked at PRs per week. It's not a perfect measure, but I think it's a useful one.

| member | PRs | weeks | PRs / week |
| ----------- | ------ | -------- | --------------- | 
| @Changaco | [134](https://github.com/gratipay/gratipay.com/search?utf8=%E2%9C%93&q=author%3Achangaco+is%3Apr+created%3A%3E2013-12-06&type=Issues) | 59 | 2.27 |
| @whit537 | [289](https://github.com/gratipay/gratipay.com/search?utf8=%E2%9C%93&q=author%3Awhit537+is%3Apr+created%3A%3E2013-07-02&type=Issues) | 82 | 3.52 |
| @rummik | [2](https://github.com/gratipay/gratipay.com/search?utf8=%E2%9C%93&q=author%3Arummik+is%3Apr+created%3A%3E2014-12-01&type=Issues) + [0](https://github.com/gratipay/grtp.co/search?utf8=%E2%9C%93&q=author%3Arummik+is%3Apr+created%3A%3E2014-12-01&type=Issues) | 8 | 0.25 |
| @rohitpaulk | [43](https://github.com/gratipay/gratipay.com/search?utf8=%E2%9C%93&q=author%3Arohitpaulk+is%3Apr+created%3A%3E2014-08-29&type=Issues) | 21 | 2.05 |
| @benhc123 | [6](https://github.com/gratipay/gratipay.com/search?utf8=%E2%9C%93&q=author%3Abenhc123+is%3Apr+created%3A%3E2014-11-10&type=Issues) | 11 | 0.55 |
| @techtonik | [11](https://github.com/gratipay/gratipay.com/search?utf8=%E2%9C%93&q=author%3Atechtonik+is%3Apr+created%3A%3E2014-10-28&type=Issues) | 13 | 0.85 |

**Comment by whit537** [comment]
> that's not the only metric to consider.

We *do* want to allow for variation due to life circumstances and local cost of living.

We should also recognize that PRs, while in my view our most important way to contribute, are not the only way to contribute:

 - Certainly one can spend a lot of time and energy contributing to discussions on tickets, though since the Internet is so full of people willing to contribute to our discussions I would tend to give a low weight to discussion on tickets. 
 - Handling support carries more weight in my view.
 - Design, marketing, or administrative tasks could also carry weight, but we haven't really seen specialists in these join the team.

**Comment by rohitpaulk** [comment]
My aim is to take $50 per week, and have enough work to support it.

For me, @Changaco is the reference point. I feel that currently, judging by both quality and quantity, my work is worth around half of what he takes. 

I didn't contribute much in December (just support requests), and I reduced my take to $25 when I realized that I was also possibly preventing others from increasing their takes. 

When I joined Gratipay, there wasn't a lack of funds - I could see at least a $50 space for me to fill without encroaching upon our running costs. That's not possible right now, but I'm sure that we'll do better in 2015. :)

**Comment by whit537** [comment]
@rummik @benhc123 @techtonik Your PRs per week are low compared to the amount of money you're taking from the team. What's the thought process by which you've arrived at your current take amount? How can we help you get your PRs/week up? :-)

**Comment by whit537** [comment]
@rohitpaulk Thanks for sharing. I appreciate the work you've been doing, both support and PRs. It's great having someone else besides me paying attention to support, and I love that you dove right in and learned SQL in order to be able to contribute more fully. Hopefully we can find a way for you to reach your $50 goal soon! :)

**Comment by whit537** [comment]
@techtonik You were doing some good work to make our Windows development story better via Vagrant. Did you get burned out on that? Are there tickets I'm not aware of that you're blocking on?

**Comment by whit537** [comment]
@benhc123 I see that you're paying attention to the issue tracker and +1ing various tickets. I know security is a focus for you, though at this point I don't think we have a surplus of pentesting work. How can we help you make the jump from security research to development?

**Comment by whit537** [comment]
@rummik You've been doing a lot of great research lately on widgets v2, and we have a plan (#125). Are we going to see some PRs soon on that? Will I see you in Ambridge tomorrow? :)

**Comment by clone1018** [comment]
I'd like to narrow the team listing down too, there's way too many people that haven't contributed in awhile on the list.

**Comment by whit537** [comment]
> I'd like to narrow the team listing down too

I don't like brute-force removing people from the team. I'd rather drop them to a penny and only show members > 1¢ by default. See https://github.com/gratipay/gratipay.com/issues/3144.

**Comment by benhc123** [comment]
Hello. Yes, I don't have many pull requests. I think it's definitely a fair opinion that I need to reduce my take.

I would really like to help out with support though if possible. How can I do this?

**Comment by rummik** [comment]
@whit537 Should.  Most of my work has been on Widgets anyway, and I have more contributions there than on the main repo

**Comment by rummik** [comment]
@whit537 You should.  I've been having trouble getting back into the rhythm of things, but I'm doing what I can. <.<;

**Comment by rummik** [comment]
@whit537 You can expect more, though I don't think PRs are a good measurement.  Since the retreat I've been working on v2 widgets, two posts, and have started a couple side projects related to Dokku as a result of the work going toward deploying v2 on a server (see [zsh-dokku](https://github.com/rummik/zsh-dokku), and [dokku-nginx-cache](https://github.com/rummik/dokku-nginx-cache)).

Not much of this has been mentioned though...and I do admit I feel like I'm running slow, but I don't know how to solve this. >.>;  If anyone has any suggestions, I'm open.

Additionally, I meant to have widgets v2 released sooner, but have been caught up in documentation and tooling, since I kind of want to have everything ready for people to go over at the same time.

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-01-27/?msg=30595559&page=2) with @rummik.

**Comment by whit537** [comment]
> I think it's definitely a fair opinion that I need to reduce my take.

@benhc123 Thank you.

> I would really like to help out with support though if possible. How can I do this?

Sure thing! I've just invited you to Freshdesk using the email address you originally emailed me from. Here's [how to support users](http://inside.gratipay.com/howto/support-users).

**Comment by Changaco** [comment]
This seems to have stalled. What now ?

**Comment by whit537** [comment]
@techtonik has popped his head up at https://github.com/gratipay/gratipay.com/issues/3149 and https://github.com/gratipay/grtp.co/pull/79#commits-pushed-ee4ad0e, so I take it he's noticed this conversation even if he's not jumping in. :-)

Closing! :dancer:

**Comment by whit537** [comment]
Also https://github.com/gratipay/grtp.co/pull/82! :-)

**Comment by techtonik** [comment]
Sorry, was absent in January. Got into financial crisis and had to limit my communication to concentrate on more sustainable stuff, but is slowly recovering now.

My +1 is that:
 * Handling support carries more weight
 * Maintainable and cross-platform design carries a lot of weight

@whit537 does a support job that I'd never manage to complete, @Changaco definitely has some AI in his basement to help him around the code, @rummik is doing some HTML5 wizardry for widgets 2.0, and I didn't have much to observe everybody else. I had more expectations for @benhc123 security exp-exp munchies, some independent opinion and analysis - this stuff is really tough and requires a lot of time to learn, and need a good skill to write reports. Basically, I compared myself to @benhc123 when setting my take, because, well, I was doing better. =) I am pretty fine how current takes are distributed. It seems fair in absolute values. As for relative ones, I am not sure anybody is able to compete with @Changaco.

I didn't reduce my take for January, because well, the half is being distributed among other projects that are important, and if I am gone and my take is reduced, the whole accumulated value will be funneled to those people. I'd be really nice to be able to reduce the distribution according to the %tage of income. As you may see, I am never short of ideas and that's a big problem.

As for team membership, it is good to have some kind of history for former team members, their active and inactive status. Simplified sparkline with takes for everybody on a timeline. And I think people should never be removed from there even if their profile is gone. Could be useful tool for projects to track their histories as a team.

History of distribution is another idea. Gratipay can be used to match donations. For example, I'd like to export my selection of receivers and percentage I give them, so that some company can match donations or see, which people need to be supported.

Another concern is that `take` is not the same as `receive`. And my widget on https://code.google.com/p/python-patch/ showing `tips/23$` is lying. I am not receiving those tips, I take them. It is not python-patch that generates those tips, it is Gratipay. So I tried to investigate user  experience on how people would really use Gratipay in practice, so #3149 is most important right now. But to tackle on it, I still stuck with development automation.

Vagrant is almost solved problem. VM management is solved, but SSH setup and packaging a new box is still a pain - https://github.com/mitchellh/vagrant/issues/created_by/techtonik Then I run into issues with our Makefile build automation, which is hard to extend - I'd still prefer to run Gratipay sites directly - working inside of VM is still slow and every VM eats memory, which had to be shared with 100+ hungry tabs in Chrome on a limited 3.2Gb notebook. So, yes, things are moving slowly. New version of pip, virtualenv, setuptools might solve some problems I had mounted with filesystem that doesn't support symlinking (https://github.com/pypa/virtualenv/pull/663),

My current focus is to executable .zip files - http://techtonik.rainforce.org/2015/01/shipping-python-tools-in-executable-zip.html - this will allow to execute invoke and other tooling directly from vendors dir without any bootstrapping. Could be a killer feature to skip the whole mess with packaging, so right now I am trying to patch distutils to produce needed .zip content. The idea is to push it to https://github.com/pyinvoke/invoke (I am still not convinced that it is a best tool for the job, so I planned to test it on grtp.co and inside after this is done).

Still learning about LXC, Doker (which sadly doesn't run on my 32bit system), and Dokku pops up twice this week, so maybe touch that too.

I still lag and can not read all the issues, but expect me to be more active already, and a Happy New Year. =)

**Comment by whit537** [comment]
Thanks for the update, @techtonik, welcome back.
