### ISSUE TITLE
better integrate translators

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#189]
We have 10 coordinators and 20 translators (are those disjoint?). Only three translators are on the [Gratipay team](https://gratipay.com/Gratipay/distributing/). Let's figure out who else should be.

![screen shot 2015-04-17 at 12 29 38 pm](https://cloud.githubusercontent.com/assets/134455/7206391/e4f33e2e-e4fe-11e4-86bd-549b21d3531a.png)

**Comment by whit537** [comment]
> [W]ould you consider creating an official Gratipay Translators team? 

https://gratipay.freshdesk.com/helpdesk/tickets/2366

**Comment by andreottidavide** [comment]
Davide here, coordinator (and translator) for the Italian language.
I personally haven't made up my mind since both cases have their own pros and cons.
For example, I think that having a separate team for translators would reduce its general visibility compared to the main team (unless multiple Gratipay teams were to be made). On the other hand, it could be specifically sought after by non-English speakers who use the service.

**Comment by whit537** [comment]
@andreottidavide Sorry for dropping the ball on this. :-(

And thank you for faithfully keeping up the Italian translation of Gratipay.com! 💃

May I add you to the [money distribution](http://inside.gratipay.com/howto/take-money)?

I am working on recovering my personal Transifex account so I can work on this further ...

**Comment by whit537** [comment]
I just went through our collaborators on Transifex and removed the 18 that haven't been "seen" for over a year, plus nashe (https://github.com/gratipay/inside.gratipay.com/issues/712#issuecomment-247981899).

**Comment by whit537** [comment]
We still have 15 translators! :-)

**Comment by whit537** [comment]
I've started our first [thread](https://www.transifex.com/gratipay/teams/25726/discussions/17277/) on our Transifex discussion board. Maybe that will reach our translators?

**Comment by andreottidavide** [comment]
Hello there, Chad.Don't worry about it.I personally have been keeping up to date with the translations themselves but haven't checked the progress of Gratipay as a whole for a few months due to time constraints (I'm just now rummaging through the site, is there any major and specific information I should know of?).
Regarding the money distribution, I have indeed no objection to being added!I have also checked the Transifex discussion you started; I'll reply to it in a minute.Have a good day,Davide Andreotti


    Il Martedì 22 Novembre 2016 17:12, Chad Whitacre <notifications@github.com> ha scritto:
 

 @andreottidavide Sorry for dropping the ball on this. :-(And thank you for faithfully keeping up the Italian translation of Gratipay.com! 💃 May I add you to the money distribution?I am working on recovering my personal Transifex account so I can work on this further ...—

**Comment by whit537** [comment]
Huzzah! 💃

> is there any major and specific information I should know of?

Probably the most significant is that we've started paying ourselves again. :-)

On the other side, we're pretty focused on trying to raise some grant funding (lastest: #637) so we can spend more time working on Gratipay!

> Regarding the money distribution, I have indeed no objection to being added!

Awesome! Here's [what we need](http://inside.gratipay.com/howto/take-money) from you.

> I have also checked the Transifex discussion you started; I'll reply to it in a minute.

Did you get an email notice about that? I don't know enough about how Transifex works ...

**Comment by andreottidavide** [comment]
> Did you get an email notice about that? I don't know enough about how Transifex works ...

@whit537 Nope, no notice from Transifex. Though if that page works like a reddit post.

> Awesome! Here's what we need from you.

I have added the only info that was missing, the identity, and if I go check my identities page, I can see it's labelled as unverified. Do I need to do something more or I'm good?

**Comment by whit537** [comment]
Yeah ... can you link your GitHub to your Gratipay for me? 😁

https://gratipay.com/on/github/andreottidavide/

**Comment by andreottidavide** [comment]
Done and done :)
 

    Il Martedì 22 Novembre 2016 23:25, Chad Whitacre <notifications@github.com> ha scritto:
 

 Yeah ... can you link your GitHub to your Gratipay for me? 😁 https://gratipay.com/on/github/andreottidavide/—

**Comment by whit537** [comment]
Added! Welcome aboard! 💃

https://gratipay.com/Gratipay/distributing/

**Comment by andreottidavide** [comment]
:thumbsup:

**Comment by whit537** [comment]
Looks like @EdOverflow is willing to help with French and German. 💃
