### ISSUE TITLE
switch jurisdictions

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#199]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100596349.

> I've been investigating the possibility of a European fork, and indeed it looks like it would be easier to run a Gratipay here than in the US.

Care to say more, @Changaco?

**Comment by Changaco** [comment]
Well it was under our nose the whole time: MangoPay has everything Gratipay needs and is fully compliant with EU financial regulations. It has an e-money emitter licence, which is something relatively new that is one level below a banking licence.

**Comment by mitar** [comment]
+1

**Comment by techtonik** [comment]
I know that many major companies who need transparency and clarity of local laws are incorporated in Cyprus. For Belarus and CIS, I don't think we have strict local laws about it, but the overall felling of complexity of our laws here gives leaves an impression that it will be a suicide to start anything connected with foreign funds here.

On the other hand, we've just got two local crowdsourcing sites, both based on Kickstarter model. They appeared at the same time, and I connect that to some legal clearance in the area. In any case would be interested to research the local matters.

**Comment by ctrlcctrlv** [comment]
Extremely likely first customers for a European Gratipay without @whit537's "corporate vision" that involves kicking out 80% of his users (source: https://twitter.com/HW_BEAT_THAT/status/596892486213054464 https://twitter.com/HW_BEAT_THAT/status/596893851454869504 ):

1. Me ( infinitydev.org )
2. weev ( twitter.com/rabite )

Likely customers (people I know but don't know if they need a funding platform):

1. WubTheCaptain ( https://partyvan.eu )
2. nekunekus ( https://pomf.se )
3. @majestrate ( i2p.rocks )

Also any small developer who happens to see my announcement on either infinitydev.org, Twitter or 8ch.net.

Let me know @Changaco. I don't have much to invest in a start up but if you need money we can discuss that too. And this time I recommend you don't involve @whit537, he's the business equivalent of rat poison seeing how quickly he tanked Gratipay (80%!).

**Comment by techtonik** [comment]
@ctrlcctrlv I am afraid that for global business, users have to choose what they want to pay for, and in the end the majority wins. But bringing the topic of social (or whatever) justice without any legal grounds to operate at all is just too premature. I would be glad if Gratipay just provided a good codebase/platform to support local communities, and communities dealt with their conflicts elsewhere. Apache server is used to host illegal sites, but Apache Foundation is not attacked by various activists because of that. It will greatly help if we could also stay away from dealing with those problems. At least for now.

**Comment by ctrlcctrlv** [comment]
@techtonik I didn't bring up any kind of justice. I brang up a source of first users, by taking advantage of @whit537's mismanagement (remember, he's only /certain/ that he wants to keep 20% of his current users - anywhere between 20 and 80% can be easily taken over by the new company in that case) of Gratipay, LLC.

The idea of a "common carrier" didn't come around for no reason. Embrace it.

**Comment by mattbk** [comment]
As much as I may disagree with #180, I think your issue with @whit537 comes off as personal rather than professional, @ctrlcctrlv. @whit537 hasn't yet booted 80 percent of users, and even this ticket wouldn't exist if he were completely set on that path. 

Regarding the issue itself, glad to see it. +1

**Comment by techtonik** [comment]
@ctrlcctrlv where is the citation about 20%? I see that we want to save Gratipay, and for that Stripe requires us to `change our business model`, so that what Gratipay does fit their rules. They will never say directly "hey, keep those money launderers away and we're all set", because it is a reputation loss risk. In reality they could only say that "hey, your service looks suspicious". But that doesn't help us to process the payday. We need to define the service, they need to ensure that it won't break their terms, and in the end we lose users. And all this is because of vague definition of "money launderers" and "suspicious service". So, it is better to find jurisdiction where the rules are not only enforced, but also explained well.

**Comment by majestrate** [comment]
@Changaco MangoPay doesn't seem to allow US based entities or Individuals, only EU based markets and crowdfunding projects. 
I would be interested in such a service. 

As an outsider to this situation I don't fully understand why @ctrlcctrlv and weev were booted, was it because they are individuals and not a project? If so would it be acceptable to utilize gratipay as a service under an umbrella project for "funposting friendly software" that may includes me, weev, fred and potentially others or does that not make sense?

**Comment by jonathan-s** [comment]
+1 for investigation.

**Comment by jonathan-s** [comment]
If investigating a change of jurisdiction Estonia might be a good option? As they offer an e-residency that makes it easier to start a company and handle legal stuff: https://e-estonia.com/e-residents/about/

**Comment by gamedevsam** [comment]
As a US resident, I'll stick with US Gratipay fork. Looking forward to see what comes out of this crazy shenanigans.

**Comment by techtonik** [comment]
@gamedevsam it may appear that the US fork is pretty much impossible due to dominance of classical bank lobbying in this country, who create rules by it is impossible to play, unless you have $500000 for a license for every state.

**Comment by mattbk** [comment]
I don't even remember posting in this issue. My +1 still stands, as disappointing as it is (as an American) to see another company "move overseas."

**Comment by mattbk** [comment]
> I don't even remember posting in this issue. My +1 still stands, as disappointing as it is (as an American) to see another company "move overseas."

Although in this case it's not to get a better tax rate or skirt labor laws, it's more in protest of how much money and power it takes to build the kind of economy we're after...

**Comment by techtonik** [comment]
@mattbk if you can get to local open data expedition folks, you can calculate how many companies are leaving because and THAT could be a good arguments for whoever wants to change the situation.
