### ISSUE TITLE
onboard @seowyanyi

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#291]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/290#issuecomment-125226538.

**Comment by whit537** [comment]
cc: @seowanyi :-)

**Comment by whit537** [comment]
cc: @seowyanyi

How can we help you get started? What sorts of things are you interested in helping with? Have you tried [setting up a development environment](https://github.com/gratipay/gratipay.com/blob/master/README.md) yet?

**Comment by mattbk** [comment]
+1 to this awesomeness.

**Comment by seowyanyi** [comment]
Hello @whit537 @mattbk
Just set up the development environment and ran all the tests. It's a breeze because of clear documentation :) I'll start with some of the issues listed!

**Comment by seowyanyi** [comment]
Hmm there are some test failures. Anyone encountered these before?

gratipay/__init__                          29      6    79%
gratipay/billing/__init__                   0      0   100%
gratipay/billing/exchanges                136     13    90%
gratipay/billing/instruments               14      3    79%
gratipay/billing/payday                   191      8    96%
gratipay/cli                               14     14     0%
gratipay/cron                              44      5    89%
gratipay/elsewhere/__init__               213     51    76%
gratipay/elsewhere/_extractors             91     37    59%
gratipay/elsewhere/_paginators             51      9    82%
gratipay/elsewhere/bitbucket               35      3    91%
gratipay/elsewhere/bountysource            60     28    53%
gratipay/elsewhere/facebook                25      0   100%
gratipay/elsewhere/github                  32      2    94%
gratipay/elsewhere/google                  26      0   100%
gratipay/elsewhere/openstreetmap           15      0   100%
gratipay/elsewhere/twitter                 24      0   100%
gratipay/elsewhere/venmo                   22      0   100%
gratipay/exceptions                        39      2    95%
gratipay/main                              57      7    88%
gratipay/models/__init__                   53      1    98%
gratipay/models/_mixin_team               127      6    95%
gratipay/models/account_elsewhere         149     21    86%
gratipay/models/community                  24      1    96%
gratipay/models/exchange_route             48      4    92%
gratipay/models/participant               614     61    90%
gratipay/models/team                       39     11    72%
gratipay/renderers/__init__                 0      0   100%
gratipay/renderers/csv_dump                18      1    94%
gratipay/renderers/jinja2_htmlescaped      11      0   100%
gratipay/security/__init__                  9      0   100%
gratipay/security/authentication           61      4    93%
gratipay/security/crypto                   95     59    38%
gratipay/security/csrf                     35      0   100%
gratipay/security/user                     42      4    90%
gratipay/testing/__init__                 137     15    89%
gratipay/testing/billing                   25      0   100%
gratipay/testing/elsewhere                 10      0   100%
gratipay/testing/emails                    14      0   100%
gratipay/testing/vcr                       26     11    58%
gratipay/utils/__init__                   155     35    77%
gratipay/utils/bitcoin                     81     44    46%
gratipay/utils/emails                      18      0   100%
gratipay/utils/fake_data                  161     17    89%
gratipay/utils/history                     97     11    89%
gratipay/utils/http_caching                40      5    88%
gratipay/utils/i18n                       144     27    81%
gratipay/utils/markdown                     4      0   100%
gratipay/utils/notifications               12      8    33%
gratipay/utils/pricing                     37     27    27%
gratipay/utils/query_cache                 95      8    92%
gratipay/utils/timer                        8      3    63%
gratipay/utils/username                    26      0   100%
gratipay/version                            8      1    88%
gratipay/wireup                           244     78    68%
-----------------------------------------------------------
TOTAL                                    3785    651    83%

===================================================== 468 passed, 59 xfailed, 3 xpassed in 125.91 seconds ======================================================
env/bin/pyflakes *.py bin gratipay tasks tests
node_modules/grunt-cli/bin/grunt test
Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:js" (jshint) task
>> 17 files lint free.

Running "jshint:tests" (jshint) task
>> 5 files lint free.

Running "aspen:start" task
Starting Aspen... started.

Running "webdriver:tests" (webdriver) task
Warning: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable; for more information, see https://github.com/ariya/phantomjs/wiki. The latest version can be downloaded from http://phantomjs.org/download.html

     Callstack:
     -> init()
 Use --force to continue.

Aborted due to warnings.

Error: Unknown signal: 6
    at ChildProcess.kill (child_process.js:1011:11)
    at process.EventEmitter.emit (events.js:95:17)
    at process.exit (node.js:707:17)
    at tryToExit (/home/seowyanyi/projects/gratipay.com/node_modules/grunt/node_modules/exit/lib/exit.js:17:15)
    at Object.exit (/home/seowyanyi/projects/gratipay.com/node_modules/grunt/node_modules/exit/lib/exit.js:34:3)
    at Object.fail.warn (/home/seowyanyi/projects/gratipay.com/node_modules/grunt/lib/grunt/fail.js:73:16)
    at /home/seowyanyi/projects/gratipay.com/node_modules/grunt-webdriver/tasks/webdriver.js:389:24
    at /home/seowyanyi/projects/gratipay.com/node_modules/grunt-webdriver/node_modules/async/lib/async.js:541:30
    at WebdriverIO.<anonymous> (/home/seowyanyi/projects/gratipay.com/node_modules/grunt-webdriver/tasks/webdriver.js:264:21)
    at WebdriverIO.<anonymous> (/home/seowyanyi/projects/gratipay.com/node_modules/grunt-webdriver/node_modules/webdriverio/lib/utils/PromiseHandler.js:152:26)
make: *** [jstest] Error 8

**Comment by whit537** [comment]
(P.S. It's best to use [code fencing](https://guides.github.com/features/mastering-markdown/) via triple-ticks (```) for formatting log output.)

**Comment by whit537** [comment]
Like this ... :-)

```
Hmm there are some test failures. Anyone encountered these before?

gratipay/__init__                          29      6    79%
gratipay/billing/__init__                   0      0   100%
gratipay/billing/exchanges                136     13    90%
gratipay/billing/instruments               14      3    79%
gratipay/billing/payday                   191      8    96%
gratipay/cli                               14     14     0%
gratipay/cron                              44      5    89%
gratipay/elsewhere/__init__               213     51    76%
gratipay/elsewhere/_extractors             91     37    59%
gratipay/elsewhere/_paginators             51      9    82%
gratipay/elsewhere/bitbucket               35      3    91%
gratipay/elsewhere/bountysource            60     28    53%
gratipay/elsewhere/facebook                25      0   100%
gratipay/elsewhere/github                  32      2    94%
gratipay/elsewhere/google                  26      0   100%
gratipay/elsewhere/openstreetmap           15      0   100%
gratipay/elsewhere/twitter                 24      0   100%
gratipay/elsewhere/venmo                   22      0   100%
gratipay/exceptions                        39      2    95%
gratipay/main                              57      7    88%
gratipay/models/__init__                   53      1    98%
gratipay/models/_mixin_team               127      6    95%
gratipay/models/account_elsewhere         149     21    86%
gratipay/models/community                  24      1    96%
gratipay/models/exchange_route             48      4    92%
gratipay/models/participant               614     61    90%
gratipay/models/team                       39     11    72%
gratipay/renderers/__init__                 0      0   100%
gratipay/renderers/csv_dump                18      1    94%
gratipay/renderers/jinja2_htmlescaped      11      0   100%
gratipay/security/__init__                  9      0   100%
gratipay/security/authentication           61      4    93%
gratipay/security/crypto                   95     59    38%
gratipay/security/csrf                     35      0   100%
gratipay/security/user                     42      4    90%
gratipay/testing/__init__                 137     15    89%
gratipay/testing/billing                   25      0   100%
gratipay/testing/elsewhere                 10      0   100%
gratipay/testing/emails                    14      0   100%
gratipay/testing/vcr                       26     11    58%
gratipay/utils/__init__                   155     35    77%
gratipay/utils/bitcoin                     81     44    46%
gratipay/utils/emails                      18      0   100%
gratipay/utils/fake_data                  161     17    89%
gratipay/utils/history                     97     11    89%
gratipay/utils/http_caching                40      5    88%
gratipay/utils/i18n                       144     27    81%
gratipay/utils/markdown                     4      0   100%
gratipay/utils/notifications               12      8    33%
gratipay/utils/pricing                     37     27    27%
gratipay/utils/query_cache                 95      8    92%
gratipay/utils/timer                        8      3    63%
gratipay/utils/username                    26      0   100%
gratipay/version                            8      1    88%
gratipay/wireup                           244     78    68%

-----------------------------------------------------------
TOTAL                                    3785    651    83%

===================================================== 468 passed, 59 xfailed, 3 xpassed in 125.91 seconds ======================================================
env/bin/pyflakes *.py bin gratipay tasks tests
node_modules/grunt-cli/bin/grunt test
Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:js" (jshint) task
>> 17 files lint free.

Running "jshint:tests" (jshint) task
>> 5 files lint free.

Running "aspen:start" task
Starting Aspen... started.

Running "webdriver:tests" (webdriver) task
Warning: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable; for more information, see https://github.com/ariya/phantomjs/wiki. The latest version can be downloaded from http://phantomjs.org/download.html

     Callstack:
     -> init()
 Use --force to continue.

Aborted due to warnings.

Error: Unknown signal: 6
    at ChildProcess.kill (child_process.js:1011:11)
    at process.EventEmitter.emit (events.js:95:17)
    at process.exit (node.js:707:17)
    at tryToExit (/home/seowyanyi/projects/gratipay.com/node_modules/grunt/node_modules/exit/lib/exit.js:17:15)
    at Object.exit (/home/seowyanyi/projects/gratipay.com/node_modules/grunt/node_modules/exit/lib/exit.js:34:3)
    at Object.fail.warn (/home/seowyanyi/projects/gratipay.com/node_modules/grunt/lib/grunt/fail.js:73:16)
    at /home/seowyanyi/projects/gratipay.com/node_modules/grunt-webdriver/tasks/webdriver.js:389:24
    at /home/seowyanyi/projects/gratipay.com/node_modules/grunt-webdriver/node_modules/async/lib/async.js:541:30
    at WebdriverIO.<anonymous> (/home/seowyanyi/projects/gratipay.com/node_modules/grunt-webdriver/tasks/webdriver.js:264:21)
    at WebdriverIO.<anonymous> (/home/seowyanyi/projects/gratipay.com/node_modules/grunt-webdriver/node_modules/webdriverio/lib/utils/PromiseHandler.js:152:26)
make: *** [jstest] Error 8
```

**Comment by whit537** [comment]
@seowyanyi It looks like a problem with PhantomJS. Do you have that installed? You need it to run the javascript test suite (which is actually pretty minimal compared to the python test suite).

**Comment by whit537** [comment]
Looks like we weren't documenting the PhantomJS requirement. Fixed in https://github.com/gratipay/gratipay.com/commit/df849c73f34a03315acbb7241b2ffeac729ef5e6.

**Comment by seowyanyi** [comment]
Thanks for the tips @whit537 !

**Comment by whit537** [comment]
Cleaning up old tickets. Reopen if you like, @seowyanyi! :-)

**Comment by whit537** [comment]
Aaaaaaaaaaannnnndddd ...
