### ISSUE TITLE
How-to for reviewing team applications 

### ISSUE THREAD

**Issue by mattbk** [gratipay/inside.gratipay.com#311]
Reticketed from https://github.com/gratipay/gratipay.com/issues/3677#issuecomment-130385113.
> A how-to page about reviewing team applications should be created at http://inside.gratipay.com/.

Justification: All criteria are not clear for a team to be accepted.

**Comment by whit537** [comment]
Agreed.

**Comment by mattbk** [comment]
So far at the other ticket, I think we've ended up with two solid criteria.  In my own words, teams must show that they have a:
1. "work-first" philosophy (you can help the team before becoming a part of the team)
2. revenue plan, not just a work plan

Assessment of "matching the mission and brand values/guidelines of Gratipay" has [not been address](https://github.com/gratipay/gratipay.com/issues/3677#issuecomment-130796272).

**Comment by mattbk** [comment]
"Work-first" is not the best phrase to use because it means other things.

**Comment by mattbk** [comment]
[Include also](https://github.com/gratipay/gratipay.com/pull/3568#issuecomment-113349074):
> We'll just have it as our policy that a Review ticket must be open at least seven days before it can be decided upon.

**Comment by whit537** [comment]
> Assessment of "matching the mission and brand values/guidelines of Gratipay" has not been addressed.

@mattbk I think it's actually a negative criterion, not a positive one. The question is not, "Does this Team match our mission and brand values," but rather, "Does this Team *not* match with our mission and brand values? Does it clash too strongly for comfort?"

**Comment by whit537** [comment]
Innocent until proven guilty, in other words. The default assumption is that any given Team does not clash with our brand, and the burden of proof is on the person who wants to say that the Team *does* clash. What's the clash?

**Comment by whit537** [comment]
Page is up here: http://inside.gratipay.com/howto/review-teams.

**Comment by whit537** [comment]
I think anyone is permitted to make a case on a team review ticket that a team clashes with the Gratipay brand. But as @mattbk [says](https://github.com/gratipay/inside.gratipay.com/issues/312#issuecomment-133731116), "Even at an open company, [...] the buck has to stop somewhere." Right now the buck stops with me. I'm the final judge of whether a Team clashes too strongly with the Gratipay brand. I expect to hand that responsibility off at some point when Gratipay is further along.

And what's important: even though I'm the buck-stopper, I *still* have to make a case in public. I don't get to nix Teams without making a case and leaving sufficient time for others to weigh in. See [KanColleWidget](https://github.com/gratipay/team-review/issues/38) for an example (and see [TechRaptor](https://github.com/gratipay/team-review/issues/17) for an example of what happens when we don't make the case properly up-front).

**Comment by whit537** [comment]
@mattbk @seanstrom et al. How does the latest howto for team review look?

http://inside.gratipay.com/howto/review-teams

**Comment by seanstrom** [comment]
The wording seems pretty good. Is the idea here to focus on that we're pretty open, accepting to everyone, except for those who position themselves as not open or accepting. I know the documentation should speak for itself, but I just wanted to clarify in my words.

**Comment by mattbk** [comment]
What about the payroll checkbox and what that means?

**Comment by whit537** [comment]
@mattbk It seemed to me that if we said something about the payroll checkbox in this document, then we would also want to say something about the parallel checkboxes agreeing to public review and the entire terms of service. I don't think we need to say anything about the public review and ToS checkboxes, therefore I don't think we need to say something here about payroll.

Put another way: the point of this doc is to describe our procedure for people to review Teams. Ensuring that they've passed initial form validation doesn't need to be part of our procedure, since initial form validation is admirably performed by a computer.

**Comment by mattbk** [comment]
Ahh, I wasn't sure whether you were booting people who didn't check that box or not.

**Comment by whit537** [comment]
> Ahh, I wasn't sure whether you were booting people who didn't check that box or not.

We don't let them submit the form without checking all the agreement boxes:

https://github.com/gratipay/gratipay.com/blob/1887/www/teams/create.json.spt#L29-L34



> Is the idea here to focus on that we're pretty open, accepting to everyone, except for those who position themselves as not open or accepting.

I would tend not to use the word "accepting," because clearly we're *not* accepting of everyone. We have a ~10% rejection rate so far, and claiming to be "accepting" to me sounds

**Comment by whit537** [comment]
Sorry, comment fail ... reposting finished second comment. :-)

**Comment by whit537** [comment]
> Is the idea here to focus on that we're pretty open, accepting to everyone, except for those who position themselves as not open or accepting.

I would tend not to use the word "accepting," because clearly we're *not* accepting of everyone: we have a ~10% rejection rate so far. Claiming to be "accepting" sounds dishonest to me.

**Comment by whit537** [comment]
> except for those who position themselves as not open or accepting.

This exception isn't sufficient, either: a community such as 8chan is in a real sense *more* open and accepting than we are, because their formal rules for exclusion are much looser than ours. Their *informal* rules *do* have a tendency to exclude people, but having to depend on this formal/informal distinction weakens the force of the exception.

**Comment by whit537** [comment]
>  Their *informal* rules *do* have a tendency to exclude people

In the sense of driving them away, because of the discomfort of being exposed to the unrestrained behavior of others.

**Comment by whit537** [comment]
We're linking to the new howto as of https://github.com/gratipay/gratipay.com/pull/3717. Closing here. Reticket any additional issues with the Review Teams howto.
