### ISSUE TITLE
onboard @fenryxo

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#342]
Per #3780:

> I would like to help with Gratipay development

This is a thread dedicate to any questions you have as you get started, @fenryxo. :-)

May I add you as a contributor on GitHub so that you can work together with the rest of us in topic branches, instead of on a fork?

**Comment by fenryxo** [comment]
> May I add you as a contributor on GitHub so that you can work together with the rest of us in topic branches, instead of on a fork?

Yes, that would be more convenient. Thanks :-)

The `make fake` issue is fixed, so I went on with `make pytest` and reported gratipay/gratipay.com#3789.

**Comment by whit537** [comment]
> Yes, that would be more convenient. Thanks :-)

Invite sent! Welcome aboard! :-)

> The `make fake` issue is fixed, so I went on with `make pytest` and reported gratipay/gratipay.com#3789.

Right, sorry, will get to that presently ...

**Comment by fenryxo** [comment]
`make pytest` goes well with the latest fix. I'm now having an issue with `make jstest`: gratipay/gratipay.com#3069

**Comment by fenryxo** [comment]
Hi @whit537. Just in case you have wondered why you haven't heard anything from me lately: I don't have much spare time as I would like to fulfil the most useless, annoying and boring PhD study duties this term in order to have more time for far more awesome stuff afterwards :-) I follow Gratipay development passively by reading e-mails from Gratipay's Github repositories and I'm looking forward to be more active since January/February ;-)

**Comment by whit537** [comment]
Thanks for the heads-up, @fenryxo. Happy to leave this ticket open for the time being. Good luck with your PhD! :-)

**Comment by fenryxo** [comment]
Hello @whit537. I expect to have more time from next weekend, so I'm going to read through the Inside Gratipay portal to jump into the Gratipay development eventually :-)

**Comment by whit537** [comment]
Nice!

@rohitpaulk Can you help @fenryxo get oriented and find a good first ticket to work on?

**Comment by rohitpaulk** [comment]
@fenryxo - https://github.com/gratipay/gratipay.com/issues/835 would be a good entry point to get your feet wet :) That ticket in itself is quite huge to tackle all at once, since it involves many tables. We're knocking them down one by one - https://github.com/gratipay/gratipay.com/pull/3896 is the latest PR. 

The documentation on IG *might* be outdated, so feel free to leave notes/questions here if anything seems fishy.

**Comment by fenryxo** [comment]
Hello. I'm sorry that I haven't responded for a long time. My boss increased my contract at the end of January, so I've been working full-time now and the amount of my free time has decreased significantly. Therefore, it's very unlikely I'll get around to Gratipay development in the near future.

**Comment by whit537** [comment]
Thanks for closing the loop, @fenryxo. Best wishes and I'm sure we'll see you around! :-)
