### ISSUE TITLE
track Open Collective

### ISSUE THREAD

**Issue by mitar** [gratipay/inside.gratipay.com#458]
[OpenCollective](https://opencollective.com/) is similar in some ways to Gratipay. It is interesting to read their blog post about how to workaround the regulation issues: https://medium.com/@xdamman/a-new-form-of-association-for-the-internet-generation-part-2-fe6d8415f444

**Comment by whit537** [comment]
Thanks, @mitar, and cc: @xdamman.

I've noted Open Collective in 180168f59b97d2a2da4dcf42b223b101564f5cf0 and at https://github.com/gratipay/inside.gratipay.com/issues/324#issuecomment-169540761.

Looks like Open Collective is pursuing companies-as-a-service (#324) using a fiscal sponsorship model (cf. @webmaven at https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100501970). It also looks like they're runnin' the ol' Silicon Valley playbook one more time, which means this could be a redux of Patreon for us. Patreon [swept](https://medium.com/gratipay-blog/how-is-gratipay-different-from-patreon-1f828d977935) Gratipay 1.0 (~= Gittip). Maybe Open Collective will sweep [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077). In which case I suppose I may as well restate what I [said](https://twitter.com/whit537/status/501936043659390976) about Patreon and [again](https://github.com/gratipay/inside.gratipay.com/issues/316#issuecomment-133363660) about Bountysource: I'll throw in the towel on Gratipay when Open Collective meets these three criteria:

 1. **They go fully open.** Private betas aren't open. So far [their GitHub](https://github.com/OpenCollective) just has their marketing site. I tried joining [their Slack](https://slack.opencollective.com/) and got a "no_perms" error. Twitter is for marketing and support, not for running a company.

 1. **They distribute revenue to both workers and owners exclusively via open, take-what-you-want payouts.** It's probably too late since they've already taken VC, and since they're not open I can't directly participate in the conversation anyway.

 1. **They're funded exclusively from pay-what-you-want soft fees—no hard fees.** Again: maybe, but who knows? They're closed. Seems unlikely given the VC round and prior startup baggage.

So far Open Collective looks to me like Meetup plus money—an incremental step, and one that might catch on, but not the evolution we're looking for with Gratipay. Open Collective looks like a way to split pizza money (cf. [Cobudget](http://cobudget.co/)), but will it be a way to openly compensate voluntary labor and capital as well?

**Comment by mitar** [comment]
Ah, I pointed out them because I think it is an interesting approach how to address regulation issues. Maybe the same thing could be done to restart Gittip 1.0. ;-)

**Comment by xdamman** [comment]
Hi there. Thanks for the ping.
I love what you guys are doing at Gratipay and you should keep going. Never throw the towel! 
We have a different approach and different opinions and that's all good. There are a lot of different needs out there.

Please don't hesitate to reach out if there are ways that we can be helpful. This is not a zero sum game and we can learn from one another.

Keep it up!

**Comment by whit537** [comment]
I received a ping in private email, pointing to "[A New Way to Fund Open Source Projects](https://medium.com/open-collective/a-new-way-to-fund-open-source-projects-91a51b1b7aac)" (with a [h/t](https://twitter.com/nayafia/status/730847171226959872) to @nayafia). Revisiting Open Collective, I'm seeing interesting signs:

1. Their GitHub now includes repos for their [frontend](https://github.com/OpenCollective/website), [API](https://github.com/OpenCollective/api), and "[app](https://github.com/OpenCollective/app)" (this is different from the frontend?).

1. Their [own OpenCollective page](https://opencollective.com/opencollective) includes their venture capital funding(!).<br>
![screen shot 2016-05-13 at 3 12 42 pm](https://cloud.githubusercontent.com/assets/134455/15259104/48e492d6-191d-11e6-8ce8-340018207026.png)

I'm reopening this ticket to track OpenCollective. :-)

**Comment by whit537** [comment]
Feelin' the burn over here! 🔥 

Just introduced someone here at Mazarine to Gratipay, made a connection re: react-boilerplate, and confirmed @nayafia's [feedback](https://github.com/gratipay/inside.gratipay.com/issues/867#issuecomment-261138485): Open Collective is kicking our ass.

# Gratipay

https://gratipay.com/react-boilerplate/

![screen shot 2016-11-17 at 3 22 18 pm](https://cloud.githubusercontent.com/assets/134455/20412122/a86b25d0-acd9-11e6-8256-9ef3fea53fad.png)

# Open Collective

https://opencollective.com/react-boilerplate

![screen shot 2016-11-17 at 3 02 40 pm](https://cloud.githubusercontent.com/assets/134455/20412030/1f571b28-acd9-11e6-89ea-fa30ce6c8431.png)

![screen shot 2016-11-17 at 3 22 50 pm](https://cloud.githubusercontent.com/assets/134455/20412135/baed9de6-acd9-11e6-962b-4948e5dfb6e8.png)

**Comment by whit537** [comment]
Picking up from https://github.com/gratipay/inside.gratipay.com/issues/867#issuecomment-261674403 ... @piamancini and I have [scheduled](https://gratipay.pipedrive.com/mail/inbox/60) a (private) call for this coming Tuesday (day after tomorrow).

Re: the #411 ...

> P.S. I'm not sure how you all manage openness and transparency at Open Collective—hopefully that's something we can discuss—but on the Gratipay side I will need to summarize our call for the Gratipay community on [this public GitHub ticket](https://github.com/gratipay/inside.gratipay.com/issues/458). 🙇

**Comment by whit537** [comment]
Okay! Thank you @piamancini for the call ... feel free to chime in as you like. 🙇

------------------------

The main take-away for me was that Gratipay is distinctive enough from Open Collective that it's worth trying to make another go of it with Gratipay.

| Thing | Open Collective | Gratipay |
|:-------|:--------------------:|:-----------:|
| business | ✅  |❌ |
| non-profit | ❌ | ❌ |
| open collective | ❌  | ✅  |

Open Collective is currently a C corp. They've raised some [investment](https://opencollective.com/faq#investors), with a 10 year vesting ("the strongest signal we could send that we're in this for the long term"). They are in the process of forming a 501(c)(3) and envision growing that to be more prominent than the C corp (cf. MySociety, Mozilla). That's the answer to how they will be more decentralized and open in the future.

My read is that Gratipay is starting from the other side. We've got the open part _down_. Now we need to figure out the institutional structure (#72) and funding for execution (#405).

Consequently, Open Collective's [open collective](https://opencollective.com/opencollective) is not mature enough that the Gratipay community could be absorbed there, even if we wanted to. They have an expense report model for sharing funds (similar to Cobudget, #554). There's no take-what-you-want compensation. You have to be hired as an employee (the three founders, currently) or contractor in order to access funds. So, while communication channels are more or less open (the Slack is working [now](https://github.com/gratipay/inside.gratipay.com/issues/458#issuecomment-169543045) ;), their own economic model is still traditional.

When Open Collective launched at the beginning of the year they were thinking more broadly in terms of social/political movements and meetups in addition to open source, but they're seeing traction in open source so are focusing there. They have almost 100 open source projects, receiving $100k/yr. They bundle open source into a "supercollective" ([c.f.](https://github.com/gratipay/gratipay.com/issues/1493)), and they "federate resources" besides money (stickers, project management).

They are Stripe in, PayPal out. They aren't underwritten by PayPal either (#305).

**Comment by whit537** [comment]
Alright! Back to work. :-)

**Comment by mitar** [comment]
> that the Gratipay community could be absorbed there

You mean, the people working on Gratipay itself. But current Gratipay end-users could probably all migrate to Open Collective and have a similar functionality experience.

So the only difference is in philosophy behind and structure? But I have not seen much differences in features to the end-user? (Here talking as an [end-user](https://opencollective.com/blaze) of Open Collective.)

**Comment by whit537** [comment]
> You mean, the people working on Gratipay itself.

Correct. The thought experiment was, "Should we quit working on Gratipay and work on Open Collective instead?" But Open Collective is not open enough for that. 😕

> But current Gratipay end-users could probably all migrate to Open Collective and have a similar functionality experience.

Yes. They basically already have. 😛
