### ISSUE TITLE
onboard @aandis

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#465]
Thanks for https://github.com/gratipay/gratipay.com/pull/3888 and https://github.com/gratipay/gratipay.com/pull/3891! May I add you as a collaborator on our GitHub organization? What do you want to work on next? :smile:

**Comment by aandis** [comment]
Sure! [#3872](https://github.com/gratipay/gratipay.com/issues/3872) looks interesting. I was also going through [#835](https://github.com/gratipay/gratipay.com/issues/835). There is some interesting read [here](https://github.com/gratipay/gratipay.com/pull/3864#issuecomment-162136220). +1 @rohitpaulk for that. Will go ahead with one of these! ;)

**Comment by whit537** [comment]
@aandis Awesome! If you have any general questions feel free to ask them here. :-)

**Comment by aandis** [comment]
:+1:

**Comment by rohitpaulk** [comment]
For reference - Second PR is at https://github.com/gratipay/gratipay.com/pull/3893 :)

**Comment by whit537** [comment]
@aandis I've sent an invite to join the Gratipay team on our GitHub org. Note that our normal pattern is to make PRs from branches in the main repo (rather than in personal forks), so that we can all collaborate on the PR as needed. Thanks for joining us! :dancer:

**Comment by aandis** [comment]
:+1:

**Comment by rohitpaulk** [comment]
We're almost done with changing the emails schema to use id instead of username (part of https://github.com/gratipay/gratipay.com/issues/835). Latest PR is https://github.com/gratipay/gratipay.com/pull/3896

@aandis - Once we've got this out of the door, I think you'd find it more fun to hack on other tickets rather than sticking to completing #835. i.e. If writing the same migrations for every table starts to get boring, move on to something else - you could help out a newbie next time and we'll eventually get #835 done. :)

Tickets that I think you'll find interesting - https://github.com/gratipay/gratipay.com/issues/3894, https://github.com/gratipay/gratipay.com/issues/3460

Issues filed under milestones are a great way to find work that is high-impact and mostly ready to work on - https://github.com/gratipay/gratipay.com/milestones (Team Basics, and Pivot - in particular)

**Comment by aandis** [comment]
Awesome! Thanks for the tip. Will check them out! :smiley:

**Comment by whit537** [comment]
!m @aandis @rohitpaulk I'm following along silently, loving what you're doing! :dancer:

**Comment by whit537** [comment]
You feelin' onboarded, @aandis? Anything else you wanna say here?

**Comment by aandis** [comment]
Nope. All good, I'll close this. :)

**Comment by TheHmadQureshi** [comment]
Welcome. :)

**Comment by whit537** [comment]
!m @aandis :dancer:
