### ISSUE TITLE
community guidelines - 2 questions

### ISSUE THREAD

**Issue by brainwane** [gratipay/inside.gratipay.com#499]
First, I just want to check that opening an issue here is the right way to start a discussion that might lead to a change in the community guidelines. Is it?

Second: "talking about others behind their back" is listed in http://inside.gratipay.com/howto/behave-well as a specific behavior that is not okay. I can see how speaking negatively about a fellow contributor and hiding that fact from them is a behavior that is usually not okay, but I also know that there have been times (in other communities) when I have prioritized safety over transparency by privately letting someone know that someone else has acted badly and that they might want to take steps to protect themselves. Sometimes we call this protective act "whisper networking".

Can you help me understand whether whisper networking is a behavior that's okay or not okay within the current "How to behave well" community guidelines? http://inside.gratipay.com/howto/deal-with-bad-behavior strongly implies it's not okay.

And does the Gratipay community think the guidelines should be changed to account for whisper networking? The guidelines could specifically make space for it. Or the guidelines could ask that people do it differently (for instance, by including the Safety Team in those conversations even when the speaker is not prepared to make a formal complaint).

I tried to look for previous conversation about this particular question but could not find it, and welcome pointers to any existing places where people already thought about this.

**Comment by mattbk** [comment]
Are you asking in the context of Gratipay users/teams, or Gratipay contributors? Inside.gratipay.com is geared more toward contributors than users.

**Comment by whit537** [comment]
> First, I just want to check that opening an issue here is the right way to start a discussion that might lead to a change in the community guidelines. Is it?

Yes.

> Inside.gratipay.com is geared more toward contributors than users.

@mattbk: are you suggesting otherwise? Or was your comment directed more at the rest of @brainwane's comments?

**Comment by whit537** [comment]
@brainwane is proposing improvements to Gratipay's [code of conduct](http://inside.gratipay.com/howto/behave-well), which is a policy that applies to contributors, who are [people conversing in our space](http://inside.gratipay.com/big-picture/welcome). We have an intentionally porous boundary between users and contributors: users (or non-users!) become contributors as soon as they post on GitHub (e.g.). Moreover, our CoC is published on Inside Gratipay (this repo).

Which is to say that the `inside.gratipay.com` repo is definitely the right place to have this discussion. :-)

**Comment by mattbk** [comment]
I'm not questioning whether it should be discussed here. I'm trying to find out whether @brainwane is asking about rules that apply to users versus rules that apply to contributors.

**Comment by whit537** [comment]
> I'm not questioning whether it should be discussed here.

Gotcha.

> I'm trying to find out whether @brainwane is asking about rules that apply to users versus rules that apply to contributors.

Yeah, the CoC applies to contributors. Are we on the same page here, @brainwane?

**Comment by brainwane** [comment]
@whit537 I believe we are on the same page about the scope of "How to Behave Well," yes. I recognize that we're talking about the guidelines that apply to the people trying to build Gratipay, as opposed to the Terms of Service governing users (as far as I understand it, that would be the Acceptable User Policy section of https://gratipay.com/about/policies/terms-of-service ).

**Comment by whit537** [comment]
> I believe we are on the same page about the scope of "How to Behave Well," yes.

Cool.

**Comment by whit537** [comment]
> Second: "talking about others behind their back" is listed in http://inside.gratipay.com/howto/behave-well as a specific behavior that is not okay.

@brainwane I love that you noticed this, because if I remember right it's the *one thing* that I "snuck in" to the Django code of conduct when I [copied it over](https://github.com/gratipay/inside.gratipay.com/commit/1524540cf72d70bc0df8dceac804c8c7de7effb8#diff-1e5248c33a27f0af866bdc88584d4170) to Inside Gratipay (well, also cussing, probably?). I knew at the time that in doing so I was stretching Gratipay's CoC a bit beyond what would be Geek Feminism Approved&trade; for a CoC. However, the Geek Feminists&trade; were pretty much all gone from the Gratipay community at that point, so there was no-one around to notice or care.

Thank you for noticing and caring! I've been caught! :smiley: :raised_hands:

**Comment by whit537** [comment]
> prioritized safety over transparency

May I try and make a subtle but vital distinction here? In writing "[Learning from Gittip](https://medium.com/gratipay-blog/learning-from-gittip-safety-and-consent-6084231ecf59)" I was careful to say that we're prioritizing safety and consent *ahead of* transparency and openness—not *over*.

The rabbit hole for this starts with @webmaven at https://github.com/gratipay/inside.gratipay.com/issues/319#issuecomment-152658069 and runs through https://github.com/gratipay/inside.gratipay.com/issues/319#issuecomment-162138787 and into #431.

We see prioritizing safety "over" transparency as implying that the two values are roughly parallel, and that there's a tension between them. We get *either* safety *or* transparency—which one will we pick? and how will we accommodate the other? Sometimes this is a helpful way to model value judgments (our mission [explanation](http://inside.gratipay.com/big-picture/mission) works with such a binary model). However, what we arrived at in #431 is a five-part "[Ladder of Love](http://inside.gratipay.com/big-picture/brand/)" in which safety is a *fundamental prerequisite* for transparency. We treat the relationship between safety and transparency as more like the relationship between C and Python than that between Ruby and Python.

![ladder-of-love](https://cloud.githubusercontent.com/assets/134455/12991912/87dcbbca-d0df-11e5-93a8-a9fa954df300.png)

Here's how we define each:

 - **love**—freely serving one another
 - **openness**—sharing control with one another
 - **transparency**—sharing information with one another
 - **consent**—not acting on another without their permission
 - **safety**—physical and emotional security

Modeled thus, as a set abstractions that build one on the other, it becomes less appropriate to talk about one value as *more important* than another, as being *higher priority* or prioritized *over* another. Which is higher priority, C or Python? Which is more important? Is C more important because Python couldn't be written without it? Or is Python more important because it makes developers so much more productive than C? That's how we think about safety and transparency. In a sense, we don't even want to admit the *possibility* of a "transparency" that somehow violates safety. For us, that would be a sham transparency. For us, there *is* no transparency without safety. For us, sharing information without safety and consent is *doxxing* or *stealing*, not transparency.

That's why we say that safety and consent must be prioritized *ahead of* (or *before*) transparency and openness, not *over* them. Safety is more important than transparency in one sense—but safety (for us) is not an end in itself! The point of safety (for us) is to *enable* the higher-order values, including transparency. Transparency depends on safety, and safety finds its fulfillment in transparency.

**Comment by whit537** [comment]
@brainwane I *am* trying to get around to actually answering your questions ... out of time for now, though. More later! :-)

**Comment by whit537** [comment]
Interesting [post](https://rework.withgoogle.com/blog/five-keys-to-a-successful-google-team/) out of Google a few months ago about how important psychological safety is as a foundation for strong teams (also noted at https://github.com/gratipay/inside.gratipay.com/issues/494#issuecomment-183432261).

**Comment by whit537** [comment]
I talked this through last night with a friend who works for a large university. I gather that, broadly speaking, [Title IX](https://en.wikipedia.org/wiki/Title_IX) is the framework for thinking about these kinds of issues within education. In that context, the standard *for employees* (as I understand it) is that: 

 1. If a person's misbehavior is worth discretely telling a friend about, then it's worth reporting to the authorities (meaning an institution's Title IX office or something like that).
 1. Any employee who learns something worth reporting is *legally required* to pass it up the chain.
 1. They're then supposed to drop out of the loop.

There is no provision for letting the authorities know *without* setting a complaint in motion, nor for being directly involved oneself after the authorities have been notified.

For students it sounds like the standard is a bit more relaxed. A student can discretely tell their friends about slimy people to watch out for without necessarily reporting it to the authorities as well—though of course the authorities encourage reporting.

In this context, "whisper networking" seems to aptly describe a behavior that's permitted for students but not for employees. A couple questions for Gratipay, then:

 - Does Gratipay want to take Title IX as a model to emulate?
 - Are our contributors more like a university's students or employees?

**Comment by whit537** [comment]
cc: @gratipay/security

**Comment by whit537** [comment]
Oops! Wrong team. :-)

**Comment by whit537** [comment]
cc: @gratipay/safety

**Comment by whit537** [comment]
The three members of the Safety Team are @dmk246 @rummik and @chrisdev.

@dmk246 and I met today to discuss this ticket.

@rummik @chrisdev Can we set up a private call or coffee either together or separately to discuss as well? Can you ping me here or on [private email](mailto:chad@zetaweb.com) with some times in the next week or two that would work for you?

**Comment by whit537** [comment]
I've heard from @chrisdev, we are scheduling a private call for next week. Haven't heard from @rummik yet.

**Comment by rummik** [comment]
Sorry.  Hadn't spotted the thread.  I could probably join in on the call, but I don't know what my availability looks like.  My life currently consists of three tech startups (one of which I'm co-founder of), a YouTube LP channel, and learning a bunch about EE, so I don't really have a lot of free time right now <.<;

**Comment by chrisdev** [comment]
@whit537 the hangout today  at 7pm is still on?

**Comment by whit537** [comment]
@chrisdev Yes!

I did also hear from @rummik. She has stepped down from the Safety Team due to busyness (though we may still meet for coffee or lunch soon if the stars align, just to catch up :). Filling @rummik's spot reticketed as #520.

**Comment by chrisdev** [comment]
:+1:

**Comment by whit537** [comment]
!m @chrisdev 
!m @dmk246 
!m @rummik 
!m @gratipay/safety :dancer:

**Comment by whit537** [comment]
Ready, @chrisdev? I emailed you ...

**Comment by whit537** [comment]
Didn't connect tonight. Will try again later this week ...

**Comment by whit537** [comment]
@chrisdev and I have rescheduled for Thursday evening (tomorrow).

**Comment by whit537** [comment]
Alright, @chrisdev and I were able to connect this evening. We met for about an hour.

> Can you help me understand whether whisper networking is a behavior that's okay or not okay within the current "How to behave well" community guidelines? http://inside.gratipay.com/howto/deal-with-bad-behavior strongly implies it's not okay.
> And does the Gratipay community think the guidelines should be changed to account for whisper networking?

@brainwane The consensus amongst the Safety Team is that you are correctly interpreting our code of conduct: "talking about others behind their back" does indeed cover what you're describing as "whisper networking," and it is indeed behavior that's not appropriate in the Gratipay contributor community. We don't intend to change our guidelines to allow for it.

Obviously, whisper networking is not behavior that we can strictly regulate, precisely because it's private. We do wish to discourage it, however. While Title IX is neither perfect nor even completely applicable to our situation, we agree with the principle that if something is important enough to discretely tell a friend, then it's important enough to report to the Safety Team. The Safety Team is to act on all reports it receives.

I'm happy to explain our reasoning further, but I also want to be respectful of your time and not give you the impression that this is a question still open for discussion.

Thank you for the chance to clarify this aspect of our code of conduct. :bow:

**Comment by brainwane** [comment]
Thank you for the clarification.

On 03/03/16 21:22, Chad Whitacre wrote:
> Alright, @chrisdev and I were able to connect this evening. We met for about an hour.
> 
>> Can you help me understand whether whisper networking is a behavior that's okay or not okay within the current "How to behave well" community guidelines? http://inside.gratipay.com/howto/deal-with-bad-behavior strongly implies it's not okay.
>> And does the Gratipay community think the guidelines should be changed to account for whisper networking?
> 
> @brainwane The consensus amongst the Safety Team is that you are correctly interpreting our code of conduct: "talking about others behind their back" does indeed cover what you're describing as "whisper networking," and it is indeed behavior that's not appropriate in the Gratipay contributor community. We don't intend to change our guidelines to allow for it.
> 
> Obviously, whisper networking is not behavior that we can strictly regulate, precisely because it's private. We do wish to discourage it, however. While Title IX is neither perfect nor even completely applicable to our situation, we agree with the principle that if something is important enough to discretely tell a friend, then it's important enough to report to the Safety Team. The Safety Team is to act on all reports it receives.
> 
> I'm happy to explain our reasoning further, but I also want to be respectful of your time and not give you the impression that this is a question still open for discussion.
> 
> Thank you for the chance to clarify this aspect of our code of conduct. :bow: 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/gratipay/inside.gratipay.com/issues/499#issuecomment-192065025
> 

-- 
Sumana Harihareswara
http://brainwane.net
