### ISSUE TITLE
Setup an AWS account for Gratipay

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/inside.gratipay.com#564]
1. Setup a root account, verify via email + attach CC
1. Create an IAM user for @rohitpaulk (and others that need it).
1. Attach the policy named `AmazonSESFullAccess` to the IAM users created.
1. Send auto-generated passwords to the users

Edit: Might be easier to create a group and assign the users to it.

**Comment by rohitpaulk** [comment]
(I need this for https://github.com/gratipay/inside.gratipay.com/issues/515)

**Comment by rohitpaulk** [comment]
http://docs.aws.amazon.com/IAM/latest/UserGuide/getting-started_create-admin-group.html

**Comment by rohitpaulk** [comment]
http://docs.aws.amazon.com/IAM/latest/UserGuide/getting-started_how-users-sign-in.html

**Comment by whit537** [comment]
Looking at this ...

**Comment by whit537** [comment]
I've recovered our Amazon account password and have signed into the AWS console.

**Comment by whit537** [comment]
Looking at groups docs ... I see "Resource Groups"—is that the same?

![screen shot 2016-04-14 at 9 32 30 am](https://cloud.githubusercontent.com/assets/134455/14529716/dea1043c-0223-11e6-8d83-8d21ee426102.png)

**Comment by whit537** [comment]
No! I found IAM ...

![screen shot 2016-04-14 at 9 35 24 am](https://cloud.githubusercontent.com/assets/134455/14529807/40d306c8-0224-11e6-8d2d-5a9ecca782e5.png)

-------------------

![screen shot 2016-04-14 at 9 34 53 am](https://cloud.githubusercontent.com/assets/134455/14529808/40d7552a-0224-11e6-8c41-2c878ec8b3e8.png)

**Comment by whit537** [comment]
I've created an administrators group and have added @rohitpaulk @clone1018 and myself to it. I've emailed login into to @rohitpaulk and @clone1018 (you should be prompted to change your password on first login).

**Comment by whit537** [comment]
I've set a password policy of minimum 12 chars and expiry after a year.

**Comment by whit537** [comment]
Double-checked, looks like we having billing configured okay.

What else do you need from me here, @rohitpaulk?

**Comment by rohitpaulk** [comment]
I'm able to login, looks good. Will reopen if anything more is needed.

**Comment by whit537** [comment]
Alright @rohitpaulk, I've added the verification record as well as the DKIM records (https://github.com/gratipay/inside.gratipay.com/issues/585#issuecomment-211986640). Is that enough to unblock you here?

**Comment by rohitpaulk** [comment]
> Is that enough to unblock you here?

Good enough for now. I'm learning this as I go, so I can't be sure of whether I'll hit roadblocks ahead :)

**Comment by whit537** [comment]
Okay, I'll keep an eye out in case we need more DNS config.

**Comment by whit537** [comment]
"Limit Increase: SES Sending Limits"

https://gratipay.freshdesk.com/helpdesk/tickets/4706

**Comment by whit537** [comment]
@rohitpaulk I've added you to the Vendors (and Security) groups in Freshdesk in case you need to interact with Amazon that way.

![screen shot 2016-04-19 at 12 57 55 pm](https://cloud.githubusercontent.com/assets/134455/14648044/6639a31e-062e-11e6-8f60-9a9818f68c20.png)

**Comment by whit537** [comment]
> Congratulations! After reviewing your case, we have increased your sending quota to 50,000 messages per day and your maximum send rate to 14 messages per second in AWS Region US West (Oregon). Your account has also been moved out of the sandbox, so you no longer need to verify recipient addresses. 
>
Please note that Amazon SES account settings are separate for each region. To increase your sending limits and move out of the sandbox in a different region, you need to open another SES Sending Limits case in Support Center unless you already submitted separate requests for multiple regions within your original case. Also, to access the region that this notice applies to from within the Amazon SES console, make sure that the region specified above is selected in the upper right corner of the console. 
>
As you get started with Amazon SES, keep in mind that you must: 
>
- Comply with the AWS Acceptable Use Policy ( http://aws.amazon.com/aup/ ) and read the Amazon SES Service Terms (section 22 of http://aws.amazon.com/service-terms/ ). 
>
- Send only high-quality emails to recipients who expect to hear from you. For more information, see http://media.amazonwebservices.com/AWS_Amazon_SES_Best_Practices.pdf. 
>
- Set up a process to handle bounces and complaints. For more information, see http://docs.aws.amazon.com/ses/latest/DeveloperGuide/bounce-complaint-notifications.html. 
>
- Use your new account to send a different type of email than you are sending from your other account(s), if applicable. For more information, see http://docs.aws.amazon.com/ses/latest/DeveloperGuide/multiple-accounts.html. 
>
We also recommend that you: 
>
- Use the Amazon SES mailbox simulator to test your system so that your testing does not adversely impact your account. For more information, see http://docs.aws.amazon.com/ses/latest/DeveloperGuide/mailbox-simulator.html. 
>
- Apply for higher sending limits before you need them. For more information, see http://docs.aws.amazon.com/ses/latest/DeveloperGuide/manage-sending-limits.html. 
>
Thank you for using Amazon SES! 

https://gratipay.freshdesk.com/helpdesk/tickets/4708

**Comment by rohitpaulk** [comment]
Hmm, looks like the domain verification failed

<img width="1419" alt="screen shot 2016-04-25 at 11 17 02 pm" src="https://cloud.githubusercontent.com/assets/3893573/14793300/077adf2e-0b3c-11e6-9848-a50d695aa9f4.png">

I've hit 'Retry'

**Comment by whit537** [comment]
Hrm ...

**Comment by rohitpaulk** [comment]
We can still send email from `support@gratipay.com` (since that email is verified), I think... 

> The email address that is sending the email. This email address must be either individually verified with Amazon SES, or from a domain that has been verified with Amazon SES

https://boto3.readthedocs.org/en/latest/reference/services/ses.html#SES.Client.send_email

I'll verify in a while

**Comment by whit537** [comment]
Failure notice: https://gratipay.freshdesk.com/helpdesk/tickets/4734.

**Comment by whit537** [comment]
Blech, yeah, I messed it up, sorry. :-/

![screen shot 2016-04-25 at 1 59 29 pm](https://cloud.githubusercontent.com/assets/134455/14793593/f90e9d70-0aed-11e6-8d3d-a00275d20de3.png)

**Comment by whit537** [comment]
Updated—@rohitpaulk retry again?

**Comment by rohitpaulk** [comment]
Hmm, I don't see a button to trigger a retry when verification is pending. I guess we'll have to wait for it to fail again? (or it just might catch your latest change in time and succeed)

**Comment by whit537** [comment]
> Congratulations! The Amazon SES verification process for the domain gratipay.com in region US West (Oregon) is now complete. You are now able to send email through Amazon SES from any address within this domain. For more information, please refer to the Amazon SES Developer Guide. 
>
Thank you for using Amazon SES.
