### ISSUE TITLE
Join Open Organization Ambassadors program

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#672]
From Opensource.com (cf. #551):

> I really hope you're doing well, and that the writing on Part 2 of your Gratipay series for Opensource.com is going smoothly.
>
I'm writing to ask two things:
>
1. Have you heard of (or seen) or Open Organization Ambassadors program?
>
2. Would you ever consider becoming an Open Organization Ambassador?
>
Here's the lowdown:
>
The program is our way of gathering together some of the most engaged and interesting members of our community—people at the forefront of this ongoing journey to introduce open source values into organizational culture (people who are doing innovative things with these values in their organizations, people from whom we all can learn about the future of work and management).
>
So far, we've had some stellar folks join us: People from different parts of the world who're really working in diverse capacities. One is working for Greenpeace. One is working in an open source community governance board. One is writing his second book about open organizations. One is a student in Singapore. In all, it's just a great group of people who like to share their ideas and move each others' work (whatever it may be) forward. Here's a bit more detail about everyone:
>
https://opensource.com/open-organization/resources/meet-ambassadors
>
We really think that your experience in a leadership capacity at Gratipay would make you an invaluable interlocutor and member of the group, which does not currently have any members doing precisely what you're doing in your position at Gratipay. Program requirements are minimal and flexible. Our primary goal here is (as in anything we do at Red Hat) to catalyze a community of like-minded thinkers working together to solve problems and share experiences. As long as we can provide value to people, we're pleased, so we'll chat with you about precisely how we'd work together. Here a program details:
>
https://opensource.com/resources/open-organization-ambassadors-program
>
Please read it over and give it some thought. You don't need to make an immediate decision, and we can pick up this discussion after your next story is published. If you'd like, I could even forward you an invitation to our monthly meeting, scheduled to occur this coming Thursday at 10:00 EST / 14:00 UTC.
>
https://opensource.com/resources/open-organization-ambassadors-program

**Comment by whit537** [comment]
Jono! cf. https://twitter.com/whit537/status/741463731641667584

**Comment by whit537** [comment]
> Invitation to attend annual All Things Open conference held in Raleigh, NC in October

I'm getting a weird result from http://allthingsopen.org/.

![screen shot 2016-06-15 at 10 23 23 am](https://cloud.githubusercontent.com/assets/134455/16083519/3fe2d406-32e3-11e6-9e3d-eb59a6aabf17.png)

**Comment by whit537** [comment]
My initial response:

> Thank you so much for the invitation! I'm going to leave this in my inbox for now. As you suggest, let's revisit after we get the next story published.

-----------------

> Actually, I've filed a GitHub ticket to avoid inbox clutter:
>
https://github.com/gratipay/inside.gratipay.com/issues/672
>
P.S. Any chance you would be willing to converse about this on GitHub instead of in private email? That would save me a fair amount of copying and pasting. :-)

**Comment by whit537** [comment]
>> Thank you so much for the invitation! I'm going to leave this in my inbox for now. As you suggest, let's revisit after we get the next story published.
>
Perfectly fine, Chad. We can always circle back.

---------------

>> P.S. Any chance you would be willing to converse about this on GitHub instead of in private email? That would save me a fair amount of copying and pasting. :-)
>
Of course! But, fair warning: I am new to GitHub so might need a little training (just joined a few weeks ago, as 'semioticrobotic,' of course.

Huzzah, @semioticrobotic! Welcome to GitHub and to Gratipay-on-GitHub! 💃 🎉 Happy to help you find your way around. :-)

**Comment by whit537** [comment]
@semioticrobotic I've been thinking on and off about your invitation to join the ambassadors program (again, thank you!). I'm interested, because Red Hat is such a successful company, and a banner-carrier for the open-source movement. After trying to get a little thing going with a few teensy companies around an "[open company](http://www.opencompany.org/)" concept, the idea of hitching my and Gratipay's wagon to Red Hat's much better-resourced "open organization" train is not without appeal.

The big question in my mind is whether Red Hat has the oomph to truly innovate here. I _love_ the [précis](https://opensource.com/open-source-way) for OpenSource.com:

> The open source way is about applying the principles of open source software development beyond software. Beyond technology. Opensource.com is about sharing how the open source way can change our world in the same way the open source model has changed software.

I recognize this from the end of *The Cathedral and the Bazaar* ([cf.](http://blog.gittip.com/post/29914417845/more-bazaars-and-better/)), and I resonate strongly with it. That is what I am trying to accomplish, as well. I guess where I struggle is that my anecdotal experience with OpenSource.com is that almost all of the content is about software and technology. What's more, this seems to be what the OpenSource.com audience _wants_, as evidenced by the poor showing my two [articles](https://github.com/gratipay/inside.gratipay.com/issues/551#issuecomment-221681728) [made](https://github.com/gratipay/inside.gratipay.com/issues/683#issuecomment-235321269) in the weekly top ten.

I guess I'd want to have a conversation about this question, and where OpenSource.com is headed editorially and strategically, before committing to being an ambassador. Is that fair?

**Comment by semioticrobotic** [comment]
@whit537 That's _more_ than fair. I really do appreciate your taking this under consideration, and I'm happy to discuss Opensource.com's editorial philosophy.

First and foremost, our mission is to shine a light on those places where open principles, values, practices, and technologies are changing the world. That's what we love doing, and that's our mandate. It's why we exist. We want Opensource.com to be a place where people gather to learn more about the ways thinking and acting openly can really alter the way to undertake all kinds of activities.

While we do publish stories featuring open source technology, we try in every case to publish stories that aren't _about_ the technology, but rather about what the technology _enables_ or _facilitates_. So, for example, we might publish an article that features an open source operating system, for example, but the "story" there isn't about new features or bugfixes, but rather about the way that operating system helps people do something new, rethink a habit our routinized way of thinking, or accomplish something cool. In the "Articles" pulldown menu, you'll see that we tend to group stories into categories ("channels") based on the domains in which we see open source operating.

The open organization channel is the newest addition to the site: a place where we can talk about the ways open principles can radically reshape organizational culture, model and procedure, and the way open values are affecting the future of work, management, and leadership. We launched it to co-incide with the publication of Jim Whitehurst's _The Open Organization_, of course, but we're always aiming for it to transcend the book itself and become something much broader (hence our preference for using lowercase when speaking about an "open organization!").

Yes, thanks to the magic and pervasiveness of search engines, technology-related topics and themes do draw a steady stream of readers to Opensource.com. But we embrace a kind of "come for the technology, stay for the philosophy" ethos that sees the "tech stuff" as the gateway to a much wider world.

We can _always_ do better about articulating this mission, but (as you know!), these things are much better done collectively—which is why our ambassadors are so vital to helping us locate, write about, and discuss topics and issues that might slip off the proverbial radar. You have so much experience thinking through the ways open values might change the way we organize around a common purpose and effort, and the way you narrate those experiences emphasizes the principles, processes, and practices—not the technologies. _That's_ exactly what we need on Opensource.com

I hope that helps clarify a bit more. Please do come right back if you'd like to hear more.

**Comment by jhibbets** [comment]
I think it's a fair assessment of what the Opensource.com audience is interested in. In fact, its taken us six years to get where we are today and we've learned a lot in those six years. At the very beginning, we were really focused on more of the philosophical parts of open source and the open source way. We discovered that we needed to include more technology in the discussion to attract a larger audience.

That being said, we're off to a similar start with open org content and conversations. It's new to many people and the audience isn't as large as the general open source population and interest. But we have learnings and experience to help grow the community faster. And that's what I think the open org ambassador program can help us accomplish. We didn't launch a community-focused program for Opensource.com until 2013 (3 years after we launched). [1] We created the open org ambassador program a few months after debuting the new editorial focus for open organizations, open leadership, and open management.

With each new ambassador, we bring in new audiences. And our ambassadors and friends are actively looking at other places where people are talking about similar topics and trying to cross-pollinate with those communities. We've been experimenting with cross-posting our content to LinkedIn Pulse and similar places where these conversations are happening to try and appeal to where this audience is. 

Those are just a few of my thoughts about it. I'm really optimistic about the potential here and completely understand your hesitations. This is a great conversation to have, so thank you for your honest and transparent feedback.

[1] https://opensource.com/life/13/2/new-community-moderator-program

**Comment by whit537** [comment]
(P.S. Looks like https://allthingsopen.org/ is back up. Reticketed #757.)

**Comment by whit537** [comment]
Thanks for weighing in, @semioticrobotic @jhibbets. Looking at the ambassador [program](https://opensource.com/resources/open-organization-ambassadors-program) requirements:

>- Provide Opensource.com with one article per month. Ambassadors can write original pieces or curate articles from writers in their respective professional networks; articles will cover pre-approved topics related to the management and leadership philosophy in _The Open Organization_.
- Regularly promote open organization-themed content via social media outlets and other open source news, leadership, and management syndication venues (news aggregators such as Reddit, Hacker News, etc.)
- Assist in leading the _Open Organization_ reading group and other management-related and leadership-related discussions
- Distribute copies of _The Open Organization_ at pre-approved, high-profile events or to strategic people in their professional networks

I would say the aspect I'm most interested in is the first one, contributing a monthly column to OpenSource.com (I think I'm basically _already_ doing the second ;).

My roots are in the open-source world, but I've long had an interest in "applying the principles of open source software development beyond software" ([src](https://opensource.com/open-source-way)). Lately I've been intentionally reaching out beyond the open source community to get involved in the collaborative economy movement (#384, #314). I find a lot of name-checking of open source there, and I think there's a lot of opportunity for "cross-pollination," as you suggest. A [toe](https://twitter.com/whit537/status/760844305518858241) in the Twitter [waters](https://twitter.com/whit537/status/760911627457748992) encourages me that OpenSource.com could be a great editorial home from which to participate in these wider conversations.

I guess I have two remaining hesitations.

The first is (I hope) minor: (3) and especially (4) don't sound like a good fit for me. I'm happy to recommend Jim's book in appropriate contexts, of course, but I'm going to be really allergic to any whiff of being simply a salesperson.

The weightier consideration is whether this is the best use of my time right now. As I write, I'm conscious of ignoring [important work](https://github.com/gratipay/gratipay.com/pull/4077) on Gratipay. I also have a half-time commitment to the Center for Open Science. Certainly I'm not going to be able to invest as much time into a monthly column as I did into #551 and #683—I don't hear you asking me to, but that's my natural inclination! For this to work, I would need to get comfortable with the idea that this can fit into my schedule.

**Comment by semioticrobotic** [comment]
All reasonable hesitations, Chad, to be sure. To perhaps assuage any lingering doubts:

> The first is (I hope) minor: (3) and especially (4) don't sound like a good fit for me. I'm happy to recommend Jim's book in appropriate contexts, of course, but I'm going to be really allergic to any whiff of being simply a salesperson.

Don't worry about the book club; that has actually concluded and we don't have any immediate plans to revive it. In fact, I we should probably adjust that language accordingly. So (3) is something of a non-issue.

As for (4), distributing copies of the book, this item describes precisely what you mention here: Mentioning and recommending the book when and where it's appropriate for you to do so. Essentially, it's just referring to the fact that we like when ambassadors keep us abreast of what they're doing and where they're headed so we can help support them in whatever way we can (and they want)—whether that's with books to distribute, or some other way that's within our power and resources. Really, though, _more_ important than putting folks "in touch" with the book is putting _people_ in touch with _us_; we love when ambassadors connect us with the people they're meeting who seem to be speaking the same language we are, or have ideas that might push us forward to challenge us. We know we just can't be everywhere, so we trust ambassadors to help us understand what's going on in their respective circles.

Since we composed that program description, we've launched 1) a monthly ambassador report (which I believe I sent you this month), and 2) a monthly, live ambassador meeting online, a (completely optional, natch) regular time for us to gather and share ideas, support one another's efforts swap best practices, get feedback, and more. In joining the program, you could count on those things, too.

And finally: the writing. This is our bread and butter (we can't really have much of a publication without published works), but we do not hold ambassadors' feet to the proverbial fire when it comes to contributing. One article per month is our suggested cadence. Some people do more; others do less. Most important to us—by far—is the notion that ambassadors derive value from being ambassadors.

**Comment by whit537** [comment]
One thing I'm seeing here is that @whit537 joining the open organization ambassador program at OpenSource.com is probably bigger/other than Gratipay. I can already imagine ten things I'd write about. Some relate to Gratipay, but not all.

1. Introducing myself
1. Why—The Ladder of Love
1. GitHub for Ambridge
1. Journalism in a collaborative society
1. From consumption to participation
1. Responding to OuiShare's decentralization experiments
1. Report on pay-what-you-want consulting
1. Report on pay-what-you-want Airbnb
1. Intro to cooperatives for open-sourcerers
1. Something re: _Designing Online Communities_
1. Something re: _Art of Community_

Okay, that was 11! :-)

Part of my thought process here is, is it time to spin up/spin out the whit537 personal brand?

I'd see my column being about "Adventures in Openness" or something like that.

**Comment by semioticrobotic** [comment]
All great ideas, @whit537. And yes, your contributions to Opensource.com need not always relate to Gratipay (in fact, we'd love if they stretched beyond it!). Topics specifically related to open principles/values and their implications for organizational culture, management and/or leadership, and the future of work would run in the open organization channel; other ideas, however, would certainly find an appreciative audience in other sections!

**Comment by whit537** [comment]
Thanks @semioticrobotic. I'm heading out for vacation momentarily, and I expect to have an answer for you one way or another when I return. Have a great week! :-)

**Comment by whit537** [comment]
Alright @semioticrobotic @jhibbets, sign me up. I will try to avoid the temptation to get _too_ involved—only one post a month on open organizations. @timothyfcook, my cofounder in the [Open Company Initiative](http://www.opencompany.org/), has agreed to be my writing buddy.

What are next steps?

P.S. You should tap @timothyfcook independently for the Education channel; you can see some of his work [here](https://medium.com/@timothyfcook).

**Comment by semioticrobotic** [comment]
Well, @whit537, this makes my day—nay, my month! So happy to have you on board. And hey: We welcome your participation in whatever form/volume you're tempted to provide it! As for next steps, I'll need just a few potentially private details from you, so I'll email you additional materials momentarily.

Thanks, too, for putting us in touch with @timothyfcook. His online resume is fascinating. Tim, we welcome your participation and contributions, too—by all means.

**Comment by whit537** [comment]
Thanks, @semioticrobotic! I've started [a new GitHub repo](https://github.com/whit537/openorg/issues) to track (my) Open Organization Ambassador program-related work, and I've replied on the members mailing list. Let's pick up with the planning for my first column [over there](https://github.com/whit537/openorg/issues/1) ...

**Comment by whit537** [comment]
https://opensource.com/open-organization/resources/meet-ambassadors

> and it has funded its our own platform

Can we change this to "and its funded on its own platform"? Thanks. :-)

**Comment by semioticrobotic** [comment]
Done and done, @whit537. Sorry for the typo.

**Comment by whit537** [comment]
No worries, @semioticrobotic—and I hate to be a pest, but could we change "and and" to "and"? 😁  🙇

**Comment by semioticrobotic** [comment]
Oops! Sorry. Fixed.

**Comment by whit537** [comment]
Awesome! Thank you, @semioticrobotic! 💃
