### ISSUE TITLE
require 2FA to be on Gratipay GitHub org

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#775]
[Kenneth got hacked](http://www.kennethreitz.org/essays/on-cybersecurity-and-being-targeted), illustrating the importance of 2FA. We should require 2FA on GitHub for anyone with permission to deploy, and maybe for everyone on the GitHub org.

**Comment by nashe** [comment]
Do you already have the percentage of 2FA activation for the Gratipay team? Requiring it for everybody would imply that everybody has long-term working phone number or the Google 
Authenticator application. However, 2FA using SMS [is being deprecated by the NIST](https://pages.nist.gov/800-63-3/sp800-63b.html) so we can expect big companies (Github?) to follow the new recommendations. 

I think that forcing it for users with access to private repositories and deploy permission is a good thing, and then strongly suggest (≠ force) to everybody in the organisation to follow the movement.

[Github has a great article about how to use all the services after enabling the 2FA](https://github.com/blog/1614-two-factor-authentication#how-does-it-work-for-command-line-git) (spoil: you may need to generate personal tokens to clone *via* https).

**Comment by whit537** [comment]
I don't have a smart phone, and I'm curious to see how long I can hold out with SMS 2FA being phased out.

All three of us on the "Deployers" team (@clone1018 @rohitpaulk @whit537) have 2FA enabled. We are at 33% overall (8 / 24).

I guess we're saying that's okay for now?

**Comment by nashe** [comment]
Yep, I think.

**Comment by whit537** [comment]
What about Heroku? And DNSimple? And MaxCDN? And Digital Ocean? Seems like we should adopt a 2FA policy for any system involved in production.

**Comment by nashe** [comment]
(and HackerOne)

**Comment by EdOverflow** [comment]
I currently use the [Google Authenticator](https://support.google.com/accounts/answer/1066447?hl=en) app, since I do not like use SMS 2FA. I also plan on getting a [yubikey](https://www.yubico.com/products/yubikey-hardware/yubikey4/). @whit537 Maybe you might want to look into a yubkiey for important accounts?

---

Here is a list of pages regarding 2FA on services we use:

- [Heroku](https://devcenter.heroku.com/articles/two-factor-authentication)
- [DNSimple](https://support.dnsimple.com/articles/two-factor-authentication/)
- [MaxCDN](https://www.turnon2fa.com/tutorials/how-to-turn-on-2fa-for-maxcdn/)
