### ISSUE TITLE
Use F6S

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#778]
A friend of mine is participating in https://www.f6s.com/fintechmarathon2016 which is 7 weeks hacking session to grow companies for FinTech business. Personally, I don't think there is any money in that, but doing business is a very complicated job, so I can use this opportunity to attract people to Gratipay to make local branch for Open Source work in Belarus. @whit537 what do you think about the idea?

Also looking at main F6S site there are more ways to seek funding. I feel like I am betraying open source community by switching to startup scene, but looking at my empty pockets I must say that I personally lost the battle. It was a really great time doing open source things and not thinking about anything.

**Comment by techtonik** [comment]
@nayafia as an expert in startups, do you think that communities like F6S are interested to support "enablement" projects like Gratipay, or they (I mean venture capital) all need to see direct profits from developers they've paid?

**Comment by nayafia** [comment]
@techtonik I'm not familiar enough with F6S, but generally speaking, for a VC, if it's not a Delaware C Corp, it's probably not investable. (This is not a values thing, VC is just an asset class that requires delivering financial returns to their investors, aka LPs!) But they might support in smaller amounts from their marketing budget, if it's a big fund (well above $100M). VCs generally take ~2% annual management fees from the total size of their fund, which pays for staff, office space, legal fees, etc, so that's a quick heuristic you can use to estimate a VC firm's operating budget. (ex. $100M fund = $2M/yr budget)

**Comment by whit537** [comment]
> I can use this opportunity to attract people to Gratipay to make local branch for Open Source work in Belarus

Sounds good to me! Let us know how it goes. Hopefully we will see some new team applications and contributors to onboard! 💃

> I feel like I am betraying open source community by switching to startup scene, but looking at my empty pockets I must say that I personally lost the battle.

Don't beat yourself up too much. I'm down to half-time on Gratipay, basically back to a side project until we can start paying ourselves again—hopefully [soon](https://github.com/gratipay/gratipay.com/issues/3994)!
