### ISSUE TITLE
404 Error on inside.gratipay.com

### ISSUE THREAD

**Issue by JessaWitzel** [gratipay/inside.gratipay.com#873]
While falling into the rabbit hole that is inside.gratipay I found a bad link. 

The welcome page: http://inside.gratipay.com/big-picture/welcome has a bad link to payroll (under the staff Role). It currently leads to this: https://gratipay.com/~Gratipay/members/ which has a 404 error on Chrome and Firefox.

**Comment by whit537** [comment]
@JessaWitzel Yes, perfect! Wanna take a shot at fixing this one? ;-) Remember to live-blog here—tell us what questions you're asking yourself and what answers you are finding—and then @mention me and/or @Gratipay if you're still stuck after an hour.

**Comment by JessaWitzel** [comment]
I found the place in the code with the broken link: https://github.com/gratipay/inside.gratipay.com/blob/378caa925798902d7b89653b35a59134db81ff1b/www/big-picture/welcome.spt (inside.gratipay.com/www/big-picture/welcome.spt) Which is the right way to reference it? 

I cannot for the life of me figure out what the correct link should be. None of the teams have members listed. I swear I've seen a page with takes from the Gratipay team but can't find it. :/ Still looking.

**Comment by kaguillera** [comment]
Soooo... Gratipay is a bit cryptic and more so since we are undergoing some major changes. 
1. First all teams are linked don't have the `~`. The `~` is only placed in links to user pages and not teams. Not sure yet why it is redirecting to `~Gratipay`. With out further research it would I would guess that it is thinking that you are looking for a user and not a team.
2. Because of the changes that we are making we have removed the members page (if it ever existed) and replaced it with distributing so the correct link (for Gratipay only at this time) for the members of the team is https://gratipay.com/Gratipay/distributing/

**Comment by kaguillera** [comment]
Please don't get discouraged it took me some looking to figure it out and I could have only been able to figure it out because I have been here for the changes that we have been making. So I had an idea/guess where to look. There are plenty of aspects of the system that I don't know and I have been working at it for about 2 yrs. I hope that does not discourage you more. 
😱

**Comment by kaguillera** [comment]
Let me know if you have any other questions.

**Comment by JessaWitzel** [comment]
Thank you!! Pull Request submitted :)
